# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atbashwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUi(self, Dialog2):
        Dialog2.setObjectName("Dialog2")
        Dialog2.resize(920, 640)
        Dialog2.setMinimumSize(QtCore.QSize(920, 640))
        Dialog2.setMaximumSize(QtCore.QSize(920, 640))
        self.but_clear = QtWidgets.QPushButton(Dialog2)
        self.but_clear.setGeometry(QtCore.QRect(760, 570, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.but_clear.setFont(font)
        self.but_clear.setObjectName("but_clear")
        self.but_encr = QtWidgets.QPushButton(Dialog2)
        self.but_encr.setGeometry(QtCore.QRect(110, 210, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.but_encr.setFont(font)
        self.but_encr.setObjectName("but_encr")
        self.label_2 = QtWidgets.QLabel(Dialog2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.but_decr = QtWidgets.QPushButton(Dialog2)
        self.but_decr.setGeometry(QtCore.QRect(110, 380, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.but_decr.setFont(font)
        self.but_decr.setObjectName("but_decr")
        self.label_3 = QtWidgets.QLabel(Dialog2)
        self.label_3.setGeometry(QtCore.QRect(20, 580, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.slova = QtWidgets.QTextEdit(Dialog2)
        self.slova.setGeometry(QtCore.QRect(330, 40, 571, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.slova.setFont(font)
        self.slova.setObjectName("slova")
        self.rez_encr = QtWidgets.QTextEdit(Dialog2)
        self.rez_encr.setGeometry(QtCore.QRect(330, 210, 571, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rez_encr.setFont(font)
        self.rez_encr.setObjectName("rez_encr")
        self.rez_decr = QtWidgets.QTextEdit(Dialog2)
        self.rez_decr.setGeometry(QtCore.QRect(330, 380, 571, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rez_decr.setFont(font)
        self.rez_decr.setObjectName("rez_decr")

        self.retranslateUi(Dialog2)
        QtCore.QMetaObject.connectSlotsByName(Dialog2)

    def retranslateUi(self, Dialog2):
        _translate = QtCore.QCoreApplication.translate
        Dialog2.setWindowTitle(_translate("Dialog2", "Шифр Атбаш"))
        self.but_clear.setText(_translate("Dialog2", "Очистить всё"))
        self.but_encr.setText(_translate("Dialog2", "Зашифровать"))
        self.label_2.setText(_translate("Dialog2", "Введите текст для шифрования:"))
        self.but_decr.setText(_translate("Dialog2", "Расшифровать"))
        self.label_3.setText(_translate("Dialog2", "* Расшифрование ведется на основе зашифрованного текста"))
