# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polibiiwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog4(object):
    def setupUi(self, Dialog4):
        Dialog4.setObjectName("Dialog4")
        Dialog4.resize(920, 640)
        Dialog4.setMinimumSize(QtCore.QSize(920, 640))
        Dialog4.setMaximumSize(QtCore.QSize(920, 640))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Dialog4.setFont(font)
        self.label_2 = QtWidgets.QLabel(Dialog4)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog4)
        self.label_3.setGeometry(QtCore.QRect(20, 580, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.but_decr = QtWidgets.QPushButton(Dialog4)
        self.but_decr.setGeometry(QtCore.QRect(100, 390, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.but_decr.setFont(font)
        self.but_decr.setObjectName("but_decr")
        self.but_clear = QtWidgets.QPushButton(Dialog4)
        self.but_clear.setGeometry(QtCore.QRect(760, 570, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.but_clear.setFont(font)
        self.but_clear.setObjectName("but_clear")
        self.but_encr = QtWidgets.QPushButton(Dialog4)
        self.but_encr.setGeometry(QtCore.QRect(100, 210, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.but_encr.setFont(font)
        self.but_encr.setObjectName("but_encr")
        self.slova = QtWidgets.QTextEdit(Dialog4)
        self.slova.setGeometry(QtCore.QRect(320, 30, 581, 151))
        self.slova.setObjectName("slova")
        self.rez_encr = QtWidgets.QTextEdit(Dialog4)
        self.rez_encr.setGeometry(QtCore.QRect(320, 210, 581, 151))
        self.rez_encr.setObjectName("rez_encr")
        self.rez_decr = QtWidgets.QTextEdit(Dialog4)
        self.rez_decr.setGeometry(QtCore.QRect(320, 390, 581, 151))
        self.rez_decr.setObjectName("rez_decr")

        self.retranslateUi(Dialog4)
        QtCore.QMetaObject.connectSlotsByName(Dialog4)

    def retranslateUi(self, Dialog4):
        _translate = QtCore.QCoreApplication.translate
        Dialog4.setWindowTitle(_translate("Dialog4", "Шифр Квадрат Полибия"))
        self.label_2.setText(_translate("Dialog4", "Введите текст для шифрования:"))
        self.label_3.setText(_translate("Dialog4", "* Расшифрование ведется на основе зашифрованного текста"))
        self.but_decr.setText(_translate("Dialog4", "Расшифровать"))
        self.but_clear.setText(_translate("Dialog4", "Очистить всё"))
        self.but_encr.setText(_translate("Dialog4", "Зашифровать"))
